### ISSUE TITLE
错误日志

### ISSUE THREAD

**Issue by dp2017** [kingschan1204/istock#10]
请问mongo数据库里的数据格式是什么样子的呢？ 系统是如何存储并提取数据的呢

**Comment by kingschan1204** [comment]
mongodb 表结构程序全部自动生成。详情可查看定时任务代码。

**Comment by dp2017** [comment]
io.github.kingschan1204.istock.module.task.SinaStockPriceTask - 深市数据更新共：0只股票,更新耗时：10ms

请问问什么会显示爬取0只股票呢？

**Comment by dp2017** [comment]
启动程序后  显示爬取0只股票  之后程序错误 并重新爬取 但还是0只股票   ，我想 是不是我的配置文件哪里出现了问题？

**Comment by kingschan1204** [comment]
StockCodeTask  这个类是负责每天晚上12点更新代码的。第一次使用程序要调用url主动去获取代码：
http://localhost/stock/refresh_code 实例化代码。这是个post类型的请求。你用postman调用就可以了。

**Comment by dp2017** [comment]
非常感谢
