### ISSUE TITLE
可以在配置文件中添加一下这个注释，东方财富

### ISSUE THREAD

**Issue by luojoe** [kingschan1204/istock#16]
![image](https://user-images.githubusercontent.com/14012817/55667124-de4f9780-588a-11e9-8eef-16179f266fee.png)
登录雪球 后打开首页 中cookie中 获取一个叫xq_a_token的参数
直接登录https://tushare.pro/user/token获取

那个东方财富网的还没发现是那个值

**Comment by luojoe** [comment]
东方财富的找到了 登录后打开http://data.eastmoney.com/rzrq/total.html 可以获取到token

**Comment by kingschan1204** [comment]
哈哈哈，感谢您提的建议 ，后续会加强的。文档这方面确实没有去完善。主要太忙了。
