### ISSUE TITLE
这个项目要改成抓取其他的网站，好改吗

### ISSUE THREAD

**Issue by WigeHuang** [kingschan1204/istock#18]
想做个爬虫爬类似的网站，你这个看起来不错，只是不符合我的要求，好改嘛

**Comment by JiangHao09** [comment]
> 想做个爬虫爬类似的网站，你这个看起来不错，只是不符合我的要求，好改嘛

不符合你的要求，你给钱了？

**Comment by WigeHuang** [comment]
误会，Sorry，我对这个不熟，问好不好改，不是叫别人改
