### ISSUE TITLE
总是提示下载失败，什么原因？

### ISSUE THREAD

**Issue by beiliefzhou** [kingschan1204/istock#21]
控制台一直提示下载某个文件失败，是什么原因？

**Comment by kingschan1204** [comment]
能贴一下具体错误信息吗？

**Comment by beiliefzhou** [comment]
![FG7)PS1VYB{Q~B%(LGW_334](https://user-images.githubusercontent.com/38290458/59481931-1251c500-8e99-11e9-9270-2972f3302d04.png)

**Comment by kingschan1204** [comment]
你在jar包同一路径下新建目录data试一下。

**Comment by beiliefzhou** [comment]
谢谢，解决了。
