### ISSUE TITLE
基本信息空白

### ISSUE THREAD

**Issue by beiliefzhou** [kingschan1204/istock#22]
我这边的基本信息是空白的。。。就是/info/{code}，这个页面一片空白，请问怎么回事呀？

**Comment by kingschan1204** [comment]
是所有空白还是个别空白

**Comment by kingschan1204** [comment]
如果是所有空白就是 没有配置好tushare.token ,另外基本信息完全采集，是在晚上12点进行的，你可以自行修改windows时间 完成实例化。

**Comment by beiliefzhou** [comment]
我是按照你说德设置的tushare.token，但是总是显示的为空。

**Comment by kingschan1204** [comment]
![微信截图_20190705160744](https://user-images.githubusercontent.com/4113891/60707773-107e9d00-9f3f-11e9-91bb-9958685b22de.png)  是这个页面为空吗？ 如果是这个界面你重新更新下代码运行  并把windows时间改到开盘时间 不出一分钟就有数据了。这个bug 我前两天刚修复的。

**Comment by beiliefzhou** [comment]
是基本信息，不是这个界面。不过5年平均股息也没有。。。
