### ISSUE TITLE
URL 不对啊 

### ISSUE THREAD

**Issue by chenxuezhou** [kingschan1204/istock#4]

**Comment by kingschan1204** [comment]
@chenxuezhou  哪个url ?

**Comment by chenxuezhou** [comment]
就是股票的数据收集URL

**Comment by kingschan1204** [comment]
这是由于有些财务数据来源于雪球网，雪球网有反爬虫的机制 ，只要登录雪球网后按F12 查出token复制到项目配置文件里即可解决问题。温馨提示报url 403错误都是这个问题。

**Comment by kingschan1204** [comment]
![1](https://user-images.githubusercontent.com/4113891/41651979-83cf2718-74b4-11e8-88d0-ce7979955304.png)
![2](https://user-images.githubusercontent.com/4113891/41651992-8b2020c6-74b4-11e8-86f0-c87c167f7ef0.png)
@chenxuezhou

**Comment by chenxuezhou** [comment]
tushare.token= 每个代码分支都没有提供，哪里可以查看这个token，也可以直接给也行
