### ISSUE TITLE
如何导入本地使用

### ISSUE THREAD

**Issue by dp2017** [kingschan1204/istock#9]
你好 ，我是学生，想要研究一下您的代码 ，请问该如何导入本地使用该程序？ 需要哪些配置？

**Comment by kingschan1204** [comment]
1.安装jdk8
2.将代码导入idea 
3.安装mongodb
4.设定配置好文件
5.运行（挂着程序就行了，定时任务会自动抓数据的）

**Comment by dp2017** [comment]
我在运行程序的时候 程序显示数据更新：0只股票，是不是我哪里弄错了呀  为什么没爬到呢？
